name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Install cli
        run: dart pub global activate code2docs_cli
        
      - name: Generate markdown files
        run: dart pub global run code2docs_cli:code2docs samples -o output        

      - name: Upload files
        run: |
         for file in $(ls -d -1 output/*) 
         do
           echo "uploading file $file"

         done
